# Generated by Django 4.2.2 on 2023-06-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_client_owner_mailing_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'permissions': [('can_view_any_mailings', 'Сan view any mailings'), ('can_disable_mailings', 'Can disable mailings')], 'verbose_name': 'Статистика (попытка)', 'verbose_name_plural': 'Статистики (попытки)'},
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активна'),
        ),
    ]
