# Generated by Django 4.2.2 on 2023-06-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_attempt_options_mailing_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'verbose_name': 'Статистика (попытка)', 'verbose_name_plural': 'Статистики (попытки)'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_any_mailings', 'Сan view any mailings'), ('can_disable_mailings', 'Can disable mailings')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
