# Generated by Django 4.2.2 on 2023-07-02 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_attempt_options_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'verbose_name': 'Попытка отправки', 'verbose_name_plural': 'Попытки отправки'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата окончания рассылки'),
        ),
    ]
