# Generated by Django 4.2.2 on 2023-06-27 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='содержимое')),
                ('preview', models.ImageField(default='posts/nophoto.png', upload_to='posts/', verbose_name='изображение')),
                ('date_of_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('number_of_views', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'ordering': ('-date_of_creation',),
            },
        ),
    ]
